spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/triplus
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 786057057179-1c4giqb03t8tlp68qkt41pnageoiva6r.apps.googleusercontent.com
            clientSecret: JmLCzJlYh-bs4iyCrzSRbWww


profiles:
  active: dev

logging:
  level:
    org.hibernate.SQL: debug

my:
  api:
    key: s3r5PXGQygPdPN0nbod5z5ro7B44y3ZU0MhLkAwYmKy652rhUS3LYDS4v9GgDbcL53oJtC1XW5Vo3q9lDc%2FndA%3D%3D