spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/triplus
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: false
  profiles:
      active: dev
  mail:
      host: smtp.gmail.com
      port: 587
      username: jiae.my.book.store@gmail.com  # 내 이메일
      password: slizncpgbjjajlie    # 내 App 패스워드
      properties:
        mail:
          smtp:
            auth: true
            timeout: 5000
            starttls.enable: true
logging:
  level:
    org.hibernate.SQL: debug

app.host: http://127.0.0.1:8080

my:
  api:
    key: s3r5PXGQygPdPN0nbod5z5ro7B44y3ZU0MhLkAwYmKy652rhUS3LYDS4v9GgDbcL53oJtC1XW5Vo3q9lDc%2FndA%3D%3D