spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/triplus;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# .gitignore 에 넣어야함!!
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 786057057179-1c4giqb03t8tlp68qkt41pnageoiva6r.apps.googleusercontent.com
            clientSecret: JmLCzJlYh-bs4iyCrzSRbWww
          facebook:
            clientId: 715398855700681
            clientSecret: 9333fb59fa8922a23709c26f82c9dadb

custom:
  oauth2:
    kakao:
      client-id: 271eef0e6400b2c07f10d224da1c7cc1
      client-secret: qmuEyZ79daA6wAOmtgnGweyBvQBVnaV0
    naver:
      client-id: VdtKZoajeHfXYfPlODRN
      client-secret: q762e5xrL7

profiles:
  active: dev

logging:
  level:
    org.hibernate.SQL: debug

my:
  api:
    key: s3r5PXGQygPdPN0nbod5z5ro7B44y3ZU0MhLkAwYmKy652rhUS3LYDS4v9GgDbcL53oJtC1XW5Vo3q9lDc%2FndA%3D%3D